github:
  repo: "turanszkij/WickedEngine"
  workflow_id: "build.yml"
  token: ""

artifacts:
  - name: "Content"
    files_to_extract: "*"
    extract_mode: "copy"

  - name: "Editor (Windows)"
    files_to_extract: "*"
    extract_mode: "copy"

output:
  download_dir: "./downloads"
  extract_dir: "./build"
  clone_dir: "./code"

state:
  last_artifact_id_file: "./last_id.txt"

telegram:
  enabled: true
  bot_token: ""
  chat_id: ""
  message_on_download: "Downloaded and unpacked fresh artifact!"

