github:
  repo: "turanszkij/WickedEngine"
  workflow_id: "build.yml"
  token: "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"

artifacts:
  - name: "Content"
    files_to_extract: "*"
    extract_mode: "copy"

  - name: "Editor (Windows)"
    files_to_extract: "*"
    extract_mode: "copy"

output:
  download_dir: "./downloads"
  extract_dir: "./build"
  clone_dir: "./code"

state:
  last_artifact_id_file: "./last_id.txt"

telegram:
  enabled: true
  bot_token: "8114307654:AAE-5yWPae2j1figslr4bbMEQMe52uObk3Q"
  chat_id: "5304944012"
  message_on_download: "Downloaded and unpacked fresh artifact!"

